### PR TITLE
Adding travis ci to the repo

### PR DESCRIPTION
**Pull request by ggfan**
Adding CI to the repo:

- use samples directory ci every check-in
- only checking build to be successful

The final one should look like this one:
- [repo](https://github.com/ggfan/testOboe)
- [ci-page](https://travis-ci.org/ggfan/testOboe)

If you are interested, let me know. In order for it to work, additional steps:

- enable travis-ci on your repo (only repo owner could do it )
- merge in this pull-request

only then could think of how to do run-time for the built samples ( emulator or firebase ci with devices )

Kindly share your thoughts: if you like it, let's the fun begin

### CODE REVIEW

**Comment by ggfan** [comment]
+ @tjohns, @philburk, @dturner

**Comment by mnaganov** [comment]
I'm not familiar with Travis so I can't tell if it's a good tool or not. The idea of having continuous integration makes sense.

Gerry, could you please confirm—is it for testing changes to Oboe against the sample apps?

**Comment by ggfan** [comment]
any change to the repo will trigger travis-ci; travis-ci will build samples. Since sample build automatically builds oboe-lib ( oboe is a static lib at current time), so oboe and samples are all get built. If there is any interface change in Oboe, samples that use that "changed interface functions/data structures" will need to be changed, otherwise build will fail immediately.

we could also add the ULT into this CI thing if needed (I saw there is a ULT directory).

**Comment by dturner** [comment]
SGTM. Gerry - OK to merge?

**Comment by ggfan** [comment]
Hey @dturner, thanks!  yeah, please help to merge it.

samples/build.gradle has some conflict, but it is really about the a version, and sequence between google() and jcenter(), google() has to be in the first due to an issue on jcenter().

After merge, 1 thing on each side:
- github repo: turn on Travis CI  service for the repo [just turn it on, no need to do anything else, I believe ]
- log in to travis-ci page, find the oboe repo ( it should show up if you are owner of the repo ), turn on CI for it

that should make it work. Thanks!

**Comment by dturner** [comment]
@ggfan - I followed your instructions but I just see "No builds for this repository" on the Travis CI page: https://travis-ci.org/google/oboe

Am I missing something? Does the setup take a while?

**Comment by dturner** [comment]
@ggfan thanks for suggesting this. I actually ran into a failed build just now: https://travis-ci.org/google/oboe/jobs/391818696

However, there wasn't any stack trace or any reason why the build failed (it was my code not compiling). Is there any way of getting more info out of Travis?

**Comment by ggfan** [comment]
the failure seems to be: 0.01s$ source .ci_tools/build_samples.sh
.ci_tools/build_samples.sh: line 15: ./gradlew: Permission denied

gradlew file does not have execution right for everyone, that needs to be added in repo.

For build, yeah, remove TERM=dumb will show lot of the logs.  ( that is inside build_sample.sh ).  probably we could enable it.  One thing is that: travis has a 4MB limit for log, as long as we do not break that limit, we are fine to lift the restriction.

**Comment by ggfan** [comment]
add PR to add x for all for gradlew ( chmod a+x gradlew )
https://github.com/google/oboe/pull/111
CI passes for that PR.

**Pull request merged**
