### PR TITLE
[Drumthumper] Allows a pad to be played while it is still pressed

### PR DESCRIPTION
**Pull request by antonioolf**
Allows a pad to be played while it is still pressed.
This allows the user to touch the same piece quickly without worrying about pressing and lifting the finger quickly.

### CODE REVIEW

**Comment by antonioolf** [comment]
@android-usb @philburk I added one more line break to match the project's code style.

**Comment by antonioolf** [comment]
@android-usb I just resolved the branch conflict. I am waiting for your code review. :relaxed:

**Review by android-usb — APPROVED** [review]
This seems reasonable.

**Comment by antonioolf** [comment]
@android-usb Great, how should I proceed now to merge it?

**Comment by dturner** [comment]
@antonioolf Thanks for submitting this. Are you able to rebase your changes on top of the current master to resolve the conflict?

**Comment by antonioolf** [comment]
@dturner Yes, of course!

**Comment by antonioolf** [comment]
@dturner rebase done and the conflict was fixed! :)

**Comment by philburk** [comment]
Note that #1041 was happening before this PR was merged so it not to blame for the break.

#1041 involves handling disconnects. This PR involves user input so I they are far enough apart to go ahead and merge.

**Pull request merged**
