### PR TITLE
Fixed: RhythmGame: After plugging in/out headphone sound was silent

### PR DESCRIPTION
**Pull request by gatzsche**

### CODE REVIEW

**Comment by gatzsche** [comment]
@googlebot I fixed it.

**Comment by gatzsche** [comment]
@googlebot I fixed it.

**Comment by gatzsche** [comment]
@googlebot I fixed it.

**Comment by gatzsche** [comment]
@googlebot I fixed it.

**Comment by dturner** [comment]
It looks like the account named "Gabriel Gatzsche" was used to make the commit but the account "gatzsche" was used to create the pull request. Both those accounts needs to have signed the CLA:

Commit: 
image

PR:
image

**Comment by philburk** [comment]
@gatzsche - If this is a fix for a bug then please file a bug first with steps for reproducing the issue.

**Comment by gatzsche** [comment]
> @gatzsche - If this is a fix for a bug then please file a bug first with steps for reproducing the issue.

Here you are:
https://github.com/google/oboe/issues/1159

**Review by porames0025 — APPROVED** [review]

**Comment by dturner** [comment]
Thanks to @porames0025 for bumping this, and apologies for the delay in merging. 

I am working on some updates to RhythmGame so will try to incorporate reviewing this change at the same time. The reason for not merging this as-is is because it may not be as simple as just restarting the stream e.g. resampling may need to be enabled.

**Comment by gatzsche** [comment]
@dturner Thanks 👍

**Review by porames0025 — APPROVED** [review]

**Comment by dturner** [comment]
@porames0025 if you would like to review and approve PRs please start contributing some code of your own first, so we can verify that you are a legit programmer with the skills required to approve other people's code changes.

If you just want something fixed, please add a thumbs up to an issue or PR.

**Review by porames0025 — APPROVED** [review]

**Comment by dturner** [comment]
@porames0025 has been blocked.

**Review by porames0025 — APPROVED** [review]

**Comment by dturner** [comment]
Should be fixed with https://github.com/google/oboe/pull/1272

**Pull request closed without merging**
