### PR TITLE
Updated all sdks, and also updated to use AndroidX as support library.

### PR DESCRIPTION
**Pull request by AndroidDeveloperLB**

### CODE REVIEW

**Comment by dturner** [comment]
Thanks for doing this. Since AndroidX is still in alpha and API 28 is still in developer preview I'm going to hold off doing this merge until both are stable.

**Comment by AndroidDeveloperLB** [comment]
But you wrote me to do this...
"Feel free to submit a pull request :)"
:(

**Comment by AndroidDeveloperLB** [comment]
BTW, Google keeps telling me that Android P DP3 is final API...

**Comment by AndroidDeveloperLB** [comment]
And I think AndroidX is the same as support library, currently, no?

**Comment by dturner** [comment]
Sorry for the confusion. I hadn't realised at the time of writing that the change would introduce non-stable dependencies. I'm currently checking with the various teams on the likelihood of API change.

**Comment by dturner** [comment]
OK, I'm reliably informed that both APIs are locked down and won't change. 

Also, I have verified the samples still run successfully on Pixel XL API 27 emulator. 

Happy to merge - good to keep things current. Thanks for submitting this.

**Pull request merged**
