### PR TITLE
fix 8KHz resampling frame buffer size for issue #751

### PR DESCRIPTION
**Pull request by erlee-hdtel**
when change the sampling rate with setSampleRate(8000), let the numFrames parameter of onAudioReady() be 20ms frame buffer size(160FPS).

### CODE REVIEW

**Comment by erlee-hdtel** [comment]
@googlebot I signed it!

**Comment by philburk** [comment]
GitHub looks for this kind of comment:
Fixes #751

**Comment by philburk** [comment]
**Thank you** for reporting the bug and finding a fix. Based on your code, I am working now on a slightly different patch that calculates the buffer size based on a 20 msec target.

**Comment by philburk** [comment]
@erlee-hdtel - Does https://github.com/google/oboe/pull/762 also fix the problem?

**Comment by erlee-hdtel** [comment]
When I run with #762 , It works good. thank you.

**Comment by philburk** [comment]
I merged #762 so I will close this one.
Thanks for reporting the problem and suggesting a fix.

**Pull request closed without merging**
