### PR TITLE
Update to Android 14

### LINKED ISSUE #1855: Update apps, samples, and tests to Android 14
With Android 14 Beta 3, developers can update their apps to SDK 34. We are currently on Android 14 Beta 4 now. We should update our apps, samples, and tests.

### PR DESCRIPTION
**Pull request by robertwu1**
Fixes #1855

### CODE REVIEW

**Review by philburk — APPROVED** [review]
I see that "Android API 34" is showing up in the Android Studio SDK Manager.

**Review by philburk — CHANGES_REQUESTED** [review]
CI is failing with:
/home/runner/work/oboe/oboe/apps/OboeTester/app/src/main/java/com/mobileer/oboetester/TestColdStartLatencyActivity.java:188: error: getDeviceId() in TestColdStartLatencyActivity cannot override getDeviceId() in ContextWrapper
    private native int getDeviceId();
                       ^
  attempting to assign weaker access privileges; was public
Note: Some input files use or override a deprecated API.

Which is odd because that file was not touched.

**Comment by philburk** [comment]
Android 14 must have added getDeviceId() to ContextWrapper!

**Comment by philburk** [comment]
Yep!
https://developer.android.com/reference/android/content/ContextWrapper#getDeviceId()

**Comment by robertwu1** [comment]
Fixed! Thanks for catching this!

**Review by philburk — APPROVED** [review]

**Pull request merged**
